const products = [
  {
    id: 'product1',
    title: 'Elephants',
    product: 'tote-bag',
    image: './img/elephants.PNG',
    price: '60',
    text: `Lorem ipsum dolor sit amet consectetur adipisicing elit.Voluptatibus quibusdam inventore pariatur vel odit adipisci quisquam! Voluptates maxime modi mollitia ut, a iste vitae itaque,excepturi nemo rem et quo ex veritatis explicabo! Repellat aassumenda laboriosam incidunt animi! Ea alias nam ab enim delenitiodio voluptatem iusto maxime temporibus!`,
  },
  {
    id: 'product2',
    title: 'Frida',
    product: 'tote-bag',
    image: './img/frida + boja.JPG',
    price: '80',
    text: `Lorem ipsum dolor sit amet consectetur adipisicing elit.Voluptatibus quibusdam inventore pariatur vel odit adipisci quisquam! Voluptates maxime modi mollitia ut, a iste vitae itaque,excepturi nemo rem et quo ex veritatis explicabo! Repellat aassumenda laboriosam incidunt animi! Ea alias nam ab enim delenitiodio voluptatem iusto maxime temporibus!`,
  },
  {
    id: 'product3',
    title: 'Karlovac',
    product: 'tote-bag',
    image: './img/karlovac.jpg',
    price: '80',
    text: `Lorem ipsum dolor sit amet consectetur adipisicing elit.Voluptatibus quibusdam inventore pariatur vel odit adipisci quisquam! Voluptates maxime modi mollitia ut, a iste vitae itaque,excepturi nemo rem et quo ex veritatis explicabo! Repellat aassumenda laboriosam incidunt animi! Ea alias nam ab enim delenitiodio voluptatem iusto maxime temporibus!`,
  },
  {
    id: 'product4',
    title: 'Komisan',
    product: 'tote-bag',
    image: './img/komisan.JPG',
    price: '80',
    text: `Lorem ipsum dolor sit amet consectetur adipisicing elit.Voluptatibus quibusdam inventore pariatur vel odit adipisci quisquam! Voluptates maxime modi mollitia ut, a iste vitae itaque,excepturi nemo rem et quo ex veritatis explicabo! Repellat aassumenda laboriosam incidunt animi! Ea alias nam ab enim delenitiodio voluptatem iusto maxime temporibus!`,
  },
  {
    id: 'product5',
    title: 'Summertime',
    product: 'tote-bag',
    image: './img/summer edition.JPG',
    price: '80',
    text: `Lorem ipsum dolor sit amet consectetur adipisicing elit.Voluptatibus quibusdam inventore pariatur vel odit adipisci quisquam! Voluptates maxime modi mollitia ut, a iste vitae itaque,excepturi nemo rem et quo ex veritatis explicabo! Repellat aassumenda laboriosam incidunt animi! Ea alias nam ab enim delenitiodio voluptatem iusto maxime temporibus!`,
  },
  {
    id: 'product6',
    title: 'Sad Owl',
    product: 'tote-bag',
    image: './img/tužna sova.jpg',
    price: '80',
    text: `Lorem ipsum dolor sit amet consectetur adipisicing elit.Voluptatibus quibusdam inventore pariatur vel odit adipisci quisquam! Voluptates maxime modi mollitia ut, a iste vitae itaque,excepturi nemo rem et quo ex veritatis explicabo! Repellat aassumenda laboriosam incidunt animi! Ea alias nam ab enim delenitiodio voluptatem iusto maxime temporibus!`,
  },
  {
    id: 'product7',
    title: 'Flowers',
    product: 'tote-bag',
    image: './img/ruže + boje.jpg',
    price: '80',
    text: `Lorem ipsum dolor sit amet consectetur adipisicing elit.Voluptatibus quibusdam inventore pariatur vel odit adipisci quisquam! Voluptates maxime modi mollitia ut, a iste vitae itaque,excepturi nemo rem et quo ex veritatis explicabo! Repellat aassumenda laboriosam incidunt animi! Ea alias nam ab enim delenitiodio voluptatem iusto maxime temporibus!`,
  },
  {
    id: 'product8',
    title: 'Dazzling lady',
    product: 'painting',
    image: './img/ruže + boje.jpg',
    price: '80',
    text: `Lorem ipsum dolor sit amet consectetur adipisicing elit.Voluptatibus quibusdam inventore pariatur vel odit adipisci quisquam! Voluptates maxime modi mollitia ut, a iste vitae itaque,excepturi nemo rem et quo ex veritatis explicabo! Repellat aassumenda laboriosam incidunt animi! Ea alias nam ab enim delenitiodio voluptatem iusto maxime temporibus!`,
  },
  {
    id: 'product9',
    title: 'Zagreb',
    product: 'tote-bag',
    image: './img/ZG.jpg',
    price: '80',
    text: `Lorem ipsum dolor sit amet consectetur adipisicing elit.Voluptatibus quibusdam inventore pariatur vel odit adipisci quisquam! Voluptates maxime modi mollitia ut, a iste vitae itaque,excepturi nemo rem et quo ex veritatis explicabo! Repellat aassumenda laboriosam incidunt animi! Ea alias nam ab enim delenitiodio voluptatem iusto maxime temporibus!`,
  },
  {
    id: 'product10',
    title: 'Sunflowers',
    product: 'tote-bag',
    image: './img/u cviću.jpg',
    price: '80',
    text: `Lorem ipsum dolor sit amet consectetur adipisicing elit.Voluptatibus quibusdam inventore pariatur vel odit adipisci quisquam! Voluptates maxime modi mollitia ut, a iste vitae itaque,excepturi nemo rem et quo ex veritatis explicabo! Repellat aassumenda laboriosam incidunt animi! Ea alias nam ab enim delenitiodio voluptatem iusto maxime temporibus!`,
  },
  {
    id: 'product11',
    title: 'Mysterious',
    product: 'tote-bag',
    image: './img/slikice.jpg',
    price: '40',
    text: `Lorem ipsum dolor sit amet consectetur adipisicing elit.Voluptatibus quibusdam inventore pariatur vel odit adipisci quisquam! Voluptates maxime modi mollitia ut, a iste vitae itaque,excepturi nemo rem et quo ex veritatis explicabo! Repellat aassumenda laboriosam incidunt animi! Ea alias nam ab enim delenitiodio voluptatem iusto maxime temporibus!`,
  },
  {
    id: 'product12',
    title: 'Mysterious',
    product: 'tote-bag',
    image: './img/slikice.jpg',
    price: '40',
    text: `Lorem ipsum dolor sit amet consectetur adipisicing elit.Voluptatibus quibusdam inventore pariatur vel odit adipisci quisquam! Voluptates maxime modi mollitia ut, a iste vitae itaque,excepturi nemo rem et quo ex veritatis explicabo! Repellat aassumenda laboriosam incidunt animi! Ea alias nam ab enim delenitiodio voluptatem iusto maxime temporibus!`,
  },
  {
    id: 'product13',
    title: 'Flowers',
    product: 'Spring Wreath',
    image: './img/slikice.jpg',
    price: '40',
    text: `Lorem ipsum dolor sit amet consectetur adipisicing elit.Voluptatibus quibusdam inventore pariatur vel odit adipisci quisquam! Voluptates maxime modi mollitia ut, a iste vitae itaque,excepturi nemo rem et quo ex veritatis explicabo! Repellat aassumenda laboriosam incidunt animi! Ea alias nam ab enim delenitiodio voluptatem iusto maxime temporibus!`,
  },
  {
    id: 'product14',
    title: 'Flowers',
    product: 'Spring Wreath',
    image: './img/spring wreath 2.jpg',
    price: '40',
    text: `Lorem ipsum dolor sit amet consectetur adipisicing elit.Voluptatibus quibusdam inventore pariatur vel odit adipisci quisquam! Voluptates maxime modi mollitia ut, a iste vitae itaque,excepturi nemo rem et quo ex veritatis explicabo! Repellat aassumenda laboriosam incidunt animi! Ea alias nam ab enim delenitiodio voluptatem iusto maxime temporibus!`,
  },
  {
    id: 'product15',
    title: 'Flowers',
    product: 'Spring Wreath',
    image: './img/spring wreath 3.jpg',
    price: '40',
    text: `Lorem ipsum dolor sit amet consectetur adipisicing elit.Voluptatibus quibusdam inventore pariatur vel odit adipisci quisquam! Voluptates maxime modi mollitia ut, a iste vitae itaque,excepturi nemo rem et quo ex veritatis explicabo! Repellat aassumenda laboriosam incidunt animi! Ea alias nam ab enim delenitiodio voluptatem iusto maxime temporibus!`,
  },
  {
    id: 'product16',
    title: 'Flowers',
    product: 'Spring Wreath',
    image: './img/spring 7.jpg',
    price: '40',
    text: `Lorem ipsum dolor sit amet consectetur adipisicing elit.Voluptatibus quibusdam inventore pariatur vel odit adipisci quisquam! Voluptates maxime modi mollitia ut, a iste vitae itaque,excepturi nemo rem et quo ex veritatis explicabo! Repellat aassumenda laboriosam incidunt animi! Ea alias nam ab enim delenitiodio voluptatem iusto maxime temporibus!`,
  },
  {
    id: 'product17',
    title: 'Flowers',
    product: 'Spring Wreath',
    image: './img/spring 8.jpg',
    price: '40',
    text: `Lorem ipsum dolor sit amet consectetur adipisicing elit.Voluptatibus quibusdam inventore pariatur vel odit adipisci quisquam! Voluptates maxime modi mollitia ut, a iste vitae itaque,excepturi nemo rem et quo ex veritatis explicabo! Repellat aassumenda laboriosam incidunt animi! Ea alias nam ab enim delenitiodio voluptatem iusto maxime temporibus!`,
  },
  {
    id: 'product18',
    title: 'Flowers',
    product: 'Spring Wreath',
    image: './img/christmas wreath.jpg ',
    price: '40',
    text: `Lorem ipsum dolor sit amet consectetur adipisicing elit.Voluptatibus quibusdam inventore pariatur vel odit adipisci quisquam! Voluptates maxime modi mollitia ut, a iste vitae itaque,excepturi nemo rem et quo ex veritatis explicabo! Repellat aassumenda laboriosam incidunt animi! Ea alias nam ab enim delenitiodio voluptatem iusto maxime temporibus!`,
  },
];

export default products;
